 // Arrays

    // Array of Questions
    const questions = [
        "What is the capital of France?",
        "Which planet is known as the Red Planet?",
        "What is the chemical symbol for water?",
        "Who wrote 'Romeo and Juliet'?",
        "What is the largest ocean on Earth?",
        "Who is known as the 'Father of Computers'?",
        "What is the main ingredient in traditional Japanese miso soup?",
        "Which element has the atomic number 1?",
        "In which year did the Titanic sink?",
        "What is the hardest natural substance on Earth?",
        "Which country is known as the Land of the Rising Sun?",
        "Who painted the Mona Lisa?",
        "Which is the smallest planet in our solar system?",
        "What is the largest mammal in the world?",
        "Who discovered penicillin?",
        "Which country hosted the 2016 Summer Olympics?",
        "What is the name of the longest river in the world?",
        "What is the smallest unit of matter?",
        "Which planet is known for its rings?",
        "Which organ is responsible for pumping blood throughout the body?"
      ];
  
      // Array of option A
      const optionA = [
        "Rome",
        "Earth",
        "H2O",
        "Charles Dickens",
        "Atlantic Ocean",
        "Alan Turing",
        "Soybeans",
        "Helium",
        "1905",
        "Gold",
        "China",
        "Vincent van Gogh",
        "Mercury",
        "Elephant",
        "Marie Curie",
        "China",
        "Amazon",
        "Molecule",
        "Venus",
        "Brain"
      ];
  
      // Array of option B
      const optionB = [
        "Madrid",
        "Mars",
        "O2",
        "William Shakespeare",
        "Indian Ocean",
        "Bill Gates",
        "Rice",
        "Hydrogen",
        "1912",
        "Iron",
        "Japan",
        "Pablo Picasso",
        "Venus",
        "Blue Whale",
        "Alexander Fleming",
        "Brazil",
        "Nile",
        "Atom",
        "Earth",
        "Lungs"
      ];
  
      // Array of option C
      const optionC = [
        "Paris",
        "Jupiter",
        "CO2",
        "Mark Twain",
        "Arctic Ocean",
        "Charles Babbage",
        "Fish",
        "Oxygen",
        "1918",
        "Diamond",
        "Thailand",
        "Leonardo da Vinci",
        "Mars",
        "Giraffe",
        "Louis Pasteur",
        "UK",
        "Mississippi",
        "Electron",
        "Neptune",
        "Heart"
      ];
  
      // Array of option D
      const optionD = [
        "Berlin",
        "Saturn",
        "NaCl",
        "Jane Austen",
        "Pacific Ocean",
        "Steve Jobs",
        "Tofu",
        "Carbon",
        "1923",
        "Platinum",
        "India",
        "Claude Monet",
        "Pluto",
        "Rhinoceros",
        "Gregor Mendel",
        "USA",
        "Yangtze",
        "Neutron",
        "Saturn",
        "Kidney"
      ];
  
      // Saving the questions which are generated by Random Num 
      const game_array = [];
      // Saving user selected options 
      const result_array = [];
      // Answers for the questions array 
      const answers = ["C", "B", "A", "B", "D", "C", "A", "B", "B", "C", "B", "C", "A", "B", "B", "B", "B", "B", "D", "C"];
  
      // Functions
  
      // Creating openQuiz Function
      function openQuiz() {
        // Hiding Entry
        let entry = document.querySelector(".entry");
        entry.setAttribute("class", "hideentry");
  
        // Un-Hiding Quiz
        let content = document.getElementById("content");
        content.removeAttribute("class");
        createQuiz();
      };
  
      // Close Quiz
      function closeQuiz() {
        // Hiding Quiz
        let content = document.getElementById("content");
        content.setAttribute("class", "hidecontent");
  
        // Un-Hiding Result
        let result = document.getElementById("result");
        result.removeAttribute("class");
  
        // Calculate and display the score
        calculateScore();
      };
  
      // Creating a Random Number
      function createQuiz() {
        let rannum;
        do {
          rannum = Math.floor(Math.random() * questions.length);
        } while (game_array.includes(rannum));
  
        game_array.push(rannum);  // Use push to maintain order
        document.getElementById("question").innerHTML = questions[rannum];
        document.getElementById("option_a").innerHTML = optionA[rannum];
        document.getElementById("option_b").innerHTML = optionB[rannum];
        document.getElementById("option_c").innerHTML = optionC[rannum];
        document.getElementById("option_d").innerHTML = optionD[rannum];
  
        if (result_array.length == 10) {
          closeQuiz();
        } else {
          console.log("Next Question");
        }
  
        return rannum;
      };
  
      // Creating saveOptionA Function
      function saveOptionA() {
        result_array.push("A");  // Use push to maintain order
        createQuiz();
      };
  
      // Creating saveOptionB Function
      function saveOptionB() {
        result_array.push("B");  // Use push to maintain order
        createQuiz();
      };
  
      // Creating saveOptionC Function
      function saveOptionC() {
        result_array.push("C");  // Use push to maintain order
        createQuiz();
      };
  
      // Creating saveOptionD Function
      function saveOptionD() {
        result_array.push("D");  // Use push to maintain order
        createQuiz();
      };
  
      // Calculate Score
      function calculateScore() {
        let score = 0;
        for (let i = 0; i < result_array.length; i++) {
          if (result_array[i] === answers[game_array[i]]) {
            score++;
          }
        }
        document.getElementById("score").innerHTML = `Your score is: ${score} / 10`;
      };
  
      // Reload Page Function
      function reloadPageOnce() {
        location.reload();
      }
  
      // Events
      // Event for Play Button
      document.getElementById('play').addEventListener('click', openQuiz);
  
      // Event for options or Clicking on Options
      // Option A 
      document.getElementById('option_a').addEventListener('click', saveOptionA);
  
      // Option B
      document.getElementById('option_b').addEventListener('click', saveOptionB);
  
      // Option C
      document.getElementById('option_c').addEventListener('click', saveOptionC);
  
      // Option D
      document.getElementById('option_d').addEventListener('click', saveOptionD);
  
      // Event for Reload Button
      document.getElementById('quit').addEventListener('click', reloadPageOnce);
      document.getElementById('playagain').addEventListener('click', reloadPageOnce);
  